### ISSUE TITLE
take a photo on mobile and upload

### ISSUE THREAD

**Issue by Hesesses** [boxxxie/angularjs-imageupload-directive#6]
When i'm trying to use the directive on mobile device (iphone 5s), i can only select photos from camera roll, not take a new photo?

Any ideas how to fix this?

**Comment by Hesesses** [comment]
Got this working, didnt know you cant use multiple attribute when using iphone.

I'm using resizing and photos taken on iphone looks like this:

![image](https://cloud.githubusercontent.com/assets/2721970/5988332/aae8f848-a964-11e4-9169-dd839299d72b.png)

**Comment by boxxxie** [comment]
the resizing code isn't mine, isn't tested, cept by exploratory means. 
I haven't used this code on a phone. 

the resize code is easy to step through, and maybe easy to break apart for testing (separate the draw from the math, and test the math). 

I accept PRs. however I recommend using another lib for images with angular, unless you want to modify my code. I can point you in the right direction to make this better, and I am motivated to make patches if you are using my code. 

currently the code doesn't behave well with ngmodel because I didn't know understand how to deal with ngModelController.

**Comment by Hesesses** [comment]
this was the problem: https://github.com/stomita/ios-imagefile-megapixel
